-keep class com.sentinel.companion.data.model.** { *; }
-keep class com.sentinel.companion.data.network.** { *; }
-keepattributes Signature
-keepattributes *Annotation*
-dontwarn okhttp3.**
-dontwarn okio.**
